### ISSUE TITLE
Specifying a path in S3 bucket for the zip file causes CodeDeploy to fail

### ISSUE THREAD

**Issue by TravellingGuy** [flxbe/strider-aws-codedeploy#3]
It's me again. :smile: 

It appears we can't specify a path in the S3 bucket to put the zip file.

For example, in the S3 Bucket field, if I enter just the bucket (`mybucket`), CodeDeploy uploads the zip file to the S3 bucket, and executes fine and my code is deployed.

However, if I specify a bucket with a path (`mybucket/path/to/zip/`), the zip is uploaded to the appropriate path in the S3 bucket, but the deploy fails at the "DownloadBundle" event with the error:

```
Error Code       UnknownError
Message          The request signature we calculated does not match the signature you provided. Check your key and signing method. 
```

The error message seems like a bit of a red herring, according to [this](http://stackoverflow.com/questions/2777078/amazon-mws-request-signature-calculated-does-not-match-the-signature-provided), that error is a catch-all, and the cause is often unrelated to keys, and can be caused by not specifying a bucket and/or path correctly (among other things).

**Comment by flxbe** [comment]
We already arrived at the final deployment, so hopefully your workflow will be working shortly 😄 
I will look into this issue later today.

**Comment by flxbe** [comment]
This should solve the issue. It was an error in the path-representation for S3.

**Comment by TravellingGuy** [comment]
Awesome, thanks, fix works.
