### ISSUE TITLE
excluding subfolder list are not working 

### ISSUE THREAD

**Issue by ratancs** [flxbe/strider-aws-codedeploy#8]
* I had to manually install zip on my EC2 instance

giving these exclude commands does not work, I still find node_modules inside my artifact

e.g. node_modules/* .git/* 

tried 
\*.git\* \*node_modules\*

http://askubuntu.com/questions/28476/how-do-i-zip-up-a-folder-but-exclude-the-git-subfolder

**Comment by flxbe** [comment]
I see the problem. The list is directly passed to the zip-command. I'd like to keep this solution since it gives complete control.

I will change the explanation on the config-page and add the link for a simple look-up. Thanks!

**Comment by flxbe** [comment]
Sorry for the late reply, I lost track of the problem over the holidays.

I fixed the explanation. The correct syntax for your use-case would be:
`node_modules/\* .git/\*`

Thanks again!
